//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.FADClassInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FADClassInfoService.FADServiceSoap")]
    public interface FADServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication1.FADClassInfoService.HelloWorldResponse HelloWorld(WebApplication1.FADClassInfoService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.HelloWorldResponse> HelloWorldAsync(WebApplication1.FADClassInfoService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrentShamsiDateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentShamsiDate", ReplyAction="*")]
        WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse GetCurrentShamsiDate(WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentShamsiDate", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse> GetCurrentShamsiDateAsync(WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FADClassInfoService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication1.FADClassInfoService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FADClassInfoService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication1.FADClassInfoService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentShamsiDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentShamsiDate", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequestBody Body;
        
        public GetCurrentShamsiDateRequest() {
        }
        
        public GetCurrentShamsiDateRequest(WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentShamsiDateRequestBody {
        
        public GetCurrentShamsiDateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentShamsiDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentShamsiDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponseBody Body;
        
        public GetCurrentShamsiDateResponse() {
        }
        
        public GetCurrentShamsiDateResponse(WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentShamsiDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentShamsiDateResult;
        
        public GetCurrentShamsiDateResponseBody() {
        }
        
        public GetCurrentShamsiDateResponseBody(string GetCurrentShamsiDateResult) {
            this.GetCurrentShamsiDateResult = GetCurrentShamsiDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FADServiceSoapChannel : WebApplication1.FADClassInfoService.FADServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FADServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.FADClassInfoService.FADServiceSoap>, WebApplication1.FADClassInfoService.FADServiceSoap {
        
        public FADServiceSoapClient() {
        }
        
        public FADServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FADServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FADServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FADServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.FADClassInfoService.HelloWorldResponse WebApplication1.FADClassInfoService.FADServiceSoap.HelloWorld(WebApplication1.FADClassInfoService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication1.FADClassInfoService.HelloWorldRequest inValue = new WebApplication1.FADClassInfoService.HelloWorldRequest();
            inValue.Body = new WebApplication1.FADClassInfoService.HelloWorldRequestBody();
            WebApplication1.FADClassInfoService.HelloWorldResponse retVal = ((WebApplication1.FADClassInfoService.FADServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.HelloWorldResponse> WebApplication1.FADClassInfoService.FADServiceSoap.HelloWorldAsync(WebApplication1.FADClassInfoService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.HelloWorldResponse> HelloWorldAsync() {
            WebApplication1.FADClassInfoService.HelloWorldRequest inValue = new WebApplication1.FADClassInfoService.HelloWorldRequest();
            inValue.Body = new WebApplication1.FADClassInfoService.HelloWorldRequestBody();
            return ((WebApplication1.FADClassInfoService.FADServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse WebApplication1.FADClassInfoService.FADServiceSoap.GetCurrentShamsiDate(WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest request) {
            return base.Channel.GetCurrentShamsiDate(request);
        }
        
        public string GetCurrentShamsiDate() {
            WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest inValue = new WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest();
            inValue.Body = new WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequestBody();
            WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse retVal = ((WebApplication1.FADClassInfoService.FADServiceSoap)(this)).GetCurrentShamsiDate(inValue);
            return retVal.Body.GetCurrentShamsiDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse> WebApplication1.FADClassInfoService.FADServiceSoap.GetCurrentShamsiDateAsync(WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest request) {
            return base.Channel.GetCurrentShamsiDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.FADClassInfoService.GetCurrentShamsiDateResponse> GetCurrentShamsiDateAsync() {
            WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest inValue = new WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequest();
            inValue.Body = new WebApplication1.FADClassInfoService.GetCurrentShamsiDateRequestBody();
            return ((WebApplication1.FADClassInfoService.FADServiceSoap)(this)).GetCurrentShamsiDateAsync(inValue);
        }
    }
}
